### PR TITLE
manifestlist_test: fix test

### PR DESCRIPTION
**Pull request by q384566678**
Signed-off-by: zhouhao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by stevvooe** [comment]
@q384566678 We really need these PRs to start including context as to why this should fail.

Please explain why you think this change should go through.

**Comment by q384566678** [comment]
@stevvooe Here I just want to add a validation, that is, in the presence of the platform, os and arch must exist. Because platform is an optional field, so here is a list of circumstances.

**Comment by vbatts** [comment]
LGTM

**Comment by stevvooe** [comment]
LGTM

**Pull request merged**
