### PR TITLE
Typo: use entrypoint instead of entry point

### PR DESCRIPTION
**Pull request by coolljt0725**
Signed-off-by: Lei Jitang <leijitang@huawei.com>

### CODE REVIEW

**Comment by vbatts** [comment]
LGTM

**Comment by brendandburns** [comment]
LGTM

**Comment by HuKeping** [comment]
non-blocking:
should it be also good to change the ones in [spec](https://github.com/opencontainers/image-spec/blob/master/serialization.md#image-json-description)

**Comment by coolljt0725** [comment]
@HuKeping  nice catch

**Comment by jonboulle** [comment]
```
15.21s$ make lint
checking lint
image/manifest.go:158::warning: Expect directory permissions to be 0700 or less,MEDIUM,HIGH (gas)
make: *** [lint] Error 1
```
o_O

**Comment by vbatts** [comment]
@jonboulle plz2lgtm #189

**Comment by vbatts** [comment]
please rebase

**Comment by coolljt0725** [comment]
@vbatts  rebased

**Comment by vbatts** [comment]
LGTM

**Comment by jonboulle** [comment]
lgtm

**Pull request merged**
