### PR TITLE
MAINTAINERS: move vbatts to EMERITUS

### PR DESCRIPTION
**Pull request by vbatts**
Happy to still be brought into conversations, but do not want to slow progress of the active maintainers.

🐐🧁🧡

### CODE REVIEW

**Review by sudo-bmitch — DISMISSED** [review]
A huge thank you for everything you've done for so many years. It won't be the same without you.
🐐🧁♥️

**Review by tianon — APPROVED** [review]
❤️

**Review by sajayantony — APPROVED** [review]
❤️

**Review by sudo-bmitch — APPROVED** [review]

**Review by jonboulle — APPROVED** [review]

**Review by cyphar — APPROVED** [review]
:heart:

**Review by sajayantony — APPROVED** [review]

**Pull request merged**
