### PR TITLE
CODEOWNERS: point to team rather than individuals

### PR DESCRIPTION
**Pull request by vbatts**
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

### CODE REVIEW

**Review by jonboulle — DISMISSED** [review]

**Review by jdolitsky — APPROVED** [review]
LGTM. This github team is now up-to-date

**Comment by tianon** [comment]
I'm not an image-spec maintainer, but figured maybe my thoughts on this are useful (being I'm a runtime-spec maintainer and this PR might end up there too).  While I agree with this in theory (DRY maintainer listing), the thing I like about `CODEOWNERS` listing individuals is that we get this:

> requested review from [brendandburns](https://github.com/brendandburns), [jonjohnsonjr](https://github.com/jonjohnsonjr), [jstarks](https://github.com/jstarks), [jonboulle](https://github.com/jonboulle), [stevvooe](https://github.com/stevvooe) and [cyphar](https://github.com/cyphar) as [code owners](https://github.com/opencontainers/image-spec/blob/02efb9a75ee11e05937b535cc5f228f9343ab2f5/CODEOWNERS#L1)

It's even easier to ignore an async ping when you can hide behind a group alias than when it's pinging one single person, so IMO this is acceptable as long as folks continue to stay active. :sweat_smile:

If this lists the team alias, do we still get individuals listed/pinged such that there's an individual call-out vs a group call-out?

**Comment by vbatts** [comment]
@tianon that is fair.

**Comment by vbatts** [comment]
I like DRYing things up, but not sure the best solution here. Closing this for cleanup. We can revisit if someone feels strongly.

**Pull request closed without merging**
