### PR TITLE
serialization: Entrypoint and Cmd nullable

### PR DESCRIPTION
**Pull request by runcom**
This is built on top of #151 - refer only to the last commit for review

@philips feel free to either cherry-pick my commit from here or wait #151 to be merged first (and I'll rebase)

This patch makes `Entrypoint` and `Cmd` fields in the serialization schema nullable + adds tests

/cc @vbatts

### CODE REVIEW

**Comment by vbatts** [comment]
not sure about this. If it is nullable, then it can be omitted. Right?

**Comment by runcom** [comment]
it should be the same as `Volumes` - it's not omitted, you get it as `Volumes: null` in the config and digest changes w/ and w/o it (this is about Docker v2s2 backward compatibility)

**Comment by vbatts** [comment]
i see. Could you rebase?

**Comment by runcom** [comment]
@vbatts done

**Comment by vbatts** [comment]
LGTM

**Comment by jonboulle** [comment]
this is unfortunate :-(

**Comment by jonboulle** [comment]
LGTM I guess

**Review by Ghostman2591 — APPROVED** [review]

**Review by Ghostman2591 — APPROVED** [review]

**Pull request merged**
