### PR TITLE
Add Travis CI and GoReportCard badge to README

### PR DESCRIPTION
**Pull request by caniszczyk**
It's nice to see the build status in the README:
https://travis-ci.org/opencontainers/image-spec

Signed-off-by: Chris Aniszczyk caniszczyk@gmail.com

### CODE REVIEW

**Comment by jonboulle** [comment]
lgtm

**Comment by wking** [comment]
On Fri, Sep 16, 2016 at 01:14:10PM -0700, Chris Aniszczyk wrote:
> It's nice to see the build status in the README:
> https://travis-ci.org/opencontainers/image-spec

Pandoc does not agree [1] ;).  Maybe @vbatts will know of a way to
make both sides happy :p.

[1]: https://travis-ci.org/opencontainers/image-spec/builds/160547704#L352

**Comment by philips** [comment]
Waiting no @vbatts to resolve

**Comment by vbatts** [comment]
<a href="https://imgflip.com/i/1b0c6j"></a>

**Comment by philips** [comment]
@vbatts so hard no on this?

**Comment by caniszczyk** [comment]
is there a way for pandoc to ignore certain things? not a blocker by any means, it's just nice to see the build status in a very visible manner

**Comment by vbatts** [comment]
ok, so I am a hard no on the badge being in the outputted 'docs'. SO, maybe the README is _only_ a landing for the github project, but the is a proper abstract/TOC/intro for the docs produced?

**Comment by vbatts** [comment]
also, i'm not sure what the situaish is here with the DCO missing. :-\

**Comment by jonboulle** [comment]
That's because I broke the PR by adding a patch. Sorry.

> SO, maybe the README is only a landing for the github project, but the is a proper abstract/TOC/intro for the docs produced?

Yes, we should do this (see also https://github.com/opencontainers/image-spec/issues/246#issuecomment-251362292)

**Comment by vbatts** [comment]
yeah. perhaps that is ideal.

**Comment by vbatts** [comment]
These two commits need to be squashed or both signed or summat

**Comment by philips** [comment]
Ping @caniszczyk

**Comment by vbatts** [comment]
kickstarting this on #433

**Pull request closed without merging**
