### PR TITLE
specs-go: add const for annotation keys

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>

### CODE REVIEW

**Comment by vbatts** [comment]
oh interesting. We had not done this yet. But why for only ref.name? there are others in annotations.md

**Comment by AkihiroSuda** [comment]
Added them.
Please review carefully so as to make sure I didn't make any typo 😄

**Comment by vbatts** [comment]
LGTM

**Comment by stevvooe** [comment]
LGTM

**Pull request merged**
