### PR TITLE
Replace ISO-8601 references with RFC-3339

### LINKED ISSUE #389: Prefer RFC-3339 over ISO-8601
The image config's `created` property is defined as anything compatible with [ISO-8601](http://www.iso.org/iso/home/standards/iso8601.htm), but this should be restricted to date/time formats compatible with [section 5.6 of RFC-3339](https://tools.ietf.org/html/rfc3339#section-5.6).

The RFC-3339 format is compatible with, but stricter than, ISO-8601 format. It removes much ambiguity and undesired variability, such as 2-digit years or the time "24:00". It is also available freely on the Internet, unlike the ISO standard.

### PR DESCRIPTION
**Pull request by aecolley**
Fixes #389

### CODE REVIEW

**Comment by philips** [comment]
LGTM

**Comment by wking** [comment]
794061e6 is missing a Signed-off-by [1], but otherwise looks good to
me.

[1]: https://travis-ci.org/opencontainers/image-spec/builds/180646050#L353

**Comment by philips** [comment]
@aecolley can you add your Signed-off-by?

**Comment by philips** [comment]
Otherwise I will resubmit this myself in 7 days.

**Comment by stevvooe** [comment]
@philips Bump.

**Comment by stevvooe** [comment]
@philips Let me know and i'll carry this.

**Comment by stevvooe** [comment]
Closing in favor of #529

**Pull request closed without merging**
