### PR TITLE
schema/manifest_backwards_compatibility_test: Fix gzip compat type

### PR DESCRIPTION
**Pull request by wking**
Catch up with #388.  I think this PR and #548 are all we missed in #388.

### CODE REVIEW

**Comment by stevvooe** [comment]
LGTM

**Comment by wking** [comment]
Rebased onto master with f077d10 → 1a24ceb.

**Comment by xiekeyang** [comment]
It looks good to me.

**Comment by jonboulle** [comment]
lgtm

**Comment by stevvooe** [comment]
LGTM

**Pull request merged**
