### PR TITLE
Replace Brendan Burns with Steve Lasker on maintainers.

### PR DESCRIPTION
**Pull request by brendandburns**
**This PR must get at least 5 LGTMs before merging:**

- [x] Brendan Burns <bburns@microsoft.com> (@brendandburns)
- [ ] Jon Johnson <jonjohnson@google.com> (@jonjohnsonjr)
- [x] John Starks <jostarks@microsoft.com> (@jstarks)
- [ ] Jonathan Boulle <jon@nstack.com> (@jonboulle)
- [ ] Stephen Day <stevvooe@gmail.com> (@stevvooe)
- [ ] Vincent Batts <vbatts@redhat.com> (@vbatts)
- [ ] Aleksa Sarai <asarai@suse.de> (@cyphar)

Signed-off-by: Brendan Burns <bburns@microsoft.com>

### CODE REVIEW

**Comment by brendandburns** [comment]
LGTM (obviously)

**Review by jstarks — APPROVED** [review]

**Review by cyphar — APPROVED** [review]
LGTM, though these atomic swaps are a bit odd tbh.

**Comment by AkihiroSuda** [comment]
needs rebase

**Comment by vbatts** [comment]
I'm not sure that these three PR's for maintainers accurately surface a maintainer election process.

It seems that while just barely, we have had a re-kindled interaction among maintainers recently, spurred by this initial audit.
Though two of the nominees (vrothberg and tych0) are not really present in reviews, PRs or the calls. Lasker is present in discussion and the calls, but not in contributions.

I move that we close these (#841 #842 #844) and among the active contributors as we continue rekindling, we have a proper nomination.

**Comment by jonboulle** [comment]
agree with vbatts - I think we can close these and reconsider "proper" nominations in the coming weeks if there's general sentiment it's desirable.

**Comment by dlorenc** [comment]
Should this be closed?

This one is different from #842 since it's a resignation and a nomination. Is there any real reason they should be coupled?

**Comment by vbatts** [comment]
Closing these three PRs (#841 #842 #844), so that adding/replacing maintainers can go through the regular nomination process

**Pull request closed without merging**
