### PR TITLE
config_test.go: Improve the verification content

### PR DESCRIPTION
**Pull request by q384566678**
Signed-off-by: zhouhao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by wking** [comment]
8076384 looks good to me.

**Comment by q384566678** [comment]
@stevvooe @vbatts @philips @jonboulle @jonboulle PTAL

**Comment by jonboulle** [comment]
lgtm

**Comment by stevvooe** [comment]
lgtm

**Pull request merged**
