### PR TITLE
use a bulleted list for rules in many places

### PR DESCRIPTION
**Pull request by erikh**
Hope this is a welcome change. Thanks!

### CODE REVIEW

**Comment by jonboulle** [comment]
would we want to do this more broadly?

**Comment by vbatts** [comment]
LGTM
and sure it could be applied to other places as well

**Comment by erikh** [comment]
Yeah I will do it!

**Comment by erikh** [comment]
I've expanded things a bit to include lists in other places. Hopefully it works.

I will do more just at a later point. Please consider this ready for merge unless it needs edits.

**Comment by philips** [comment]
LGTM

**Comment by vbatts** [comment]
LGTM

**Comment by jonboulle** [comment]
ugh, I'm not so happy about this; it doesn't make sense in sections that are English prose.

**Comment by erikh** [comment]
sorry! Let me know what you're objecting to and I will revert it manually.

**Comment by stevvooe** [comment]
@erikh I actually agree with @jonboulle here. This does not help readability.

**Comment by stevvooe** [comment]
@vbatts Can we revert this?

**Comment by vbatts** [comment]
I guess, but it would be post-v1.0.0

**Comment by stevvooe** [comment]
Seems like this can go in the v1.0.0. This is pretty awful.

**Comment by stevvooe** [comment]
@erikh Thanks! But it looks like this will go out with the 1.0.

**Comment by erikh** [comment]
Do you want me to do it or not?

**Comment by stevvooe** [comment]
@erikh Yes, please, but it may not be merged immediately.

**Comment by erikh** [comment]
I'm sorry, I won't have the time to do this, nor will I have much to spend on opencontainers in general.

Sorry if I caused any trouble. Thank you for letting me be involved in the past!

**Comment by vbatts** [comment]
@stevvooe this revert is going to have to be manually done.

**Comment by stevvooe** [comment]
@vbatts Yes, agreed. I'll take care of it after 1.0.

**Comment by vbatts** [comment]
:+1:

**Pull request merged**
