### PR TITLE
[ReadMe] Add Compliance Language

### PR DESCRIPTION
**Pull request by RobDolinMS**
Add language parallel to what is in the OCI Runtime.

Signed-off-by: Rob Dolin robdolin@microsoft.com

### CODE REVIEW

**Comment by philips** [comment]
Agreed, we will have entire sections of the spec that are optional vs parts of sections.

**Comment by vbatts** [comment]
This SGTM. It has a whitespace that needs to be fixed also.

**Comment by RobDolinMS** [comment]
@philips Since @wking has a few items in his comment, can you elaborate on what you agree on?

**Comment by RobDolinMS** [comment]
Per discussion on today's OCI Dev ConCall, recommendation is to have more detailed language as Trevor suggests.  

There may be a separate issue related to manifest lists.

**Comment by philips** [comment]
LGTM

We need to add clarifying language manifest list top matter but I have no further concerns for other objects.

**Comment by vbatts** [comment]
Moved to #432

**Pull request closed without merging**
