### PR TITLE
schema: delete content that is not used

### PR DESCRIPTION
**Pull request by q384566678**
The content is not called or used, and I think they may be superfluous.
Signed-off-by: zhouhao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by stevvooe** [comment]
This looks like it was copied over from the runtime-spec.

@vbatts Is there anything here that was useful?

**Comment by philips** [comment]
LGTM

**Comment by stevvooe** [comment]
LGTM

**Comment by jonboulle** [comment]
lgtm

**Pull request merged**
