### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by vbatts**
90c67b0 Merge pull request #575 from coolljt0725/fix_ref
e0f3d4b Merge pull request #574 from wking/auxilary-typo
a125828 Merge pull request #546 from vbatts/manifest-list-rename
2a0114e Merge pull request #571 from vbatts/makefile_default_target
a651ad6 Merge pull request #572 from coolljt0725/fix_typo
bba6ed8 Merge pull request #551 from stevvooe/annotations-field-on-descriptor
5ef499e Merge pull request #563 from xiekeyang/compatibility-test
c91797c Merge pull request #564 from xiekeyang/config-schema
c16fa01 Merge pull request #519 from coolljt0725/validate_layout
87410cf Merge pull request #565 from vbatts/fixup_pr533
df12019 Merge pull request #559 from vbatts/carry_pr497
e4c7ecd Merge pull request #561 from wking/no-refs-catchup
145870b Merge pull request #555 from q384566678/fix-info
27d549a Merge pull request #533 from vbatts/manifest-list-index
fec6ea3 Merge pull request #556 from mikebrow/linkfixes

### CODE REVIEW

**Comment by stevvooe** [comment]
I'd at least like to see https://github.com/opencontainers/image-spec/pull/551. The image tools project is, unfortunately, using the release tags.

**Comment by stevvooe** [comment]
Also, https://github.com/opencontainers/image-spec/pull/546 should be in here.

That would cover the most destructive changes.

Maybe #544, as well.

**Comment by coolljt0725** [comment]
@vbatts  should https://github.com/opencontainers/image-spec/pull/519 be here?

**Comment by stevvooe** [comment]
LGTM

**Comment by jbouzane** [comment]
LGTM

**Pull request merged**
