### PR TITLE
README.md: fix wrong place of period

### PR DESCRIPTION
**Pull request by TrumanLing**
Signed-off-by: Ling FaKe lingfake@huawei.com

### CODE REVIEW

**Comment by jonboulle** [comment]
Ehh, I don't think this is necessary. If you want to change it, then "every Wednesday" is better.

**Comment by TrumanLing** [comment]
@jonboulle thanks for your advice, I think it should be changed due to wrong plural `Wednesdays` and wrong place of period `.` in `(USA Pacific)`. And I have made it, PTAL.

**Comment by wking** [comment]
On Thu, Oct 27, 2016 at 07:07:31PM -0700, TrumanLing wrote:
> I think it should be changed due to wrong plural `Wednesdays` and
> wrong place of period `.` in `(USA Pacific)`.

3ef49101 looks good to me for the period fix.

I have no problem with the old “Wednesdays”, although I don't mind
“every Wednesday” either.

**Comment by jonboulle** [comment]
LGTM for fixing the periods, thanks. But as a nit, "Wednesdays" is a perfectly correct plural for this purpose.

**Comment by TrumanLing** [comment]
@jonboulle updated it, PTAL.

**Comment by wking** [comment]
432958a looks good to me.

**Comment by jonboulle** [comment]
LGTM

**Comment by philips** [comment]
LGTM

**Pull request merged**
