### PR TITLE
    MAINTAINERS: move jonboulle to EMERITUS

### PR DESCRIPTION
**Pull request by jonboulle**
Glad to have been part of this project, but it's time to recuse myself
from maintainership and make way for folks more active and engaged in
this space. Follows #1177.

### CODE REVIEW

**Review by sudo-bmitch — APPROVED** [review]
🫡♥️ Thank you for getting the spec to where we are today!

**Review by vbatts — DISMISSED** [review]
LGTM 🌄

**Review by sajayantony — APPROVED** [review]
❤️🫡

**Review by tianon — APPROVED** [review]
❤️

**Comment by sudo-bmitch** [comment]
@jonjohnsonjr @stevvooe @cyphar PTAL

**Review by stevvooe — APPROVED** [review]

**Pull request merged**
