### PR TITLE
schema: Drop self-describing media types from manifest(-list) tests

### PR DESCRIPTION
**Pull request by wking**
Catch up with #411 (and fixing test errors after rebuilding `schema/fs.go`).

Ideally we'd be testing “is `schema/fs.go` current?” in Travis, and I'm trying to handle that in #530, but it's tricky.  We can land these test fixes in the meantime, without blocking on more robust CI.

### CODE REVIEW

**Comment by stevvooe** [comment]
Make sure to remove this from manifest.md and manifest-list.md, as well.

**Comment by wking** [comment]
On Thu, Jan 26, 2017 at 01:22:35PM -0800, Stephen Day wrote:
> Make sure to remove this from manifest.md and manifest-list.md, as
> well.

Those were marked reserved by #411 (although I'd asked for them to be
removed [1]).  If the current maintainer consensus has changed to be
“they should also be removed”, I'm happy to do that in this PR (just
let me know).

[1]: https://github.com/opencontainers/image-spec/pull/411#discussion_r91774988

**Comment by wking** [comment]
On Thu, Jan 26, 2017 at 01:36:02PM -0800, W. Trevor King wrote:
> Thu, Jan 26, 2017 at 01:22:35PM -0800, Stephen Day:
> > Make sure to remove this from manifest.md and manifest-list.md, as
> > well.
> 
> Those were marked reserved by #411 (although I'd asked for them to
> be removed [1]).  If the current maintainer consensus has changed to
> be “they should also be removed”, I'm happy to do that in this PR
> (just let me know).

Or did you just mean “remove mediaType from those examples”?  That
seems less controversial to me, so I've done it with bc6f0fd →
99e6104.  Still let me know if you need anything different about the
mediaType definitions [1].

[1]: https://github.com/opencontainers/image-spec/blame/eee8749ab8dd46b26778f6d97a9d59e60aefe5d0/manifest.md#L23

**Comment by stevvooe** [comment]
LGTM

**Comment by jonboulle** [comment]
lgtm

**Pull request merged**
