### PR TITLE
specs-go/v1: use digest type on descriptor

### PR DESCRIPTION
**Pull request by stevvooe**
Signed-off-by: Stephen J Day <stephen.day@docker.com>

cc @opencontainers/image-spec-maintainers

### CODE REVIEW

**Comment by stevvooe** [comment]
Replaces #522

**Comment by wking** [comment]
On Mon, Jan 23, 2017 at 04:47:50PM -0800, Stephen Day wrote:
> Replaces #522

This is #522 ;).  Should be “Replaces #514”.

**Comment by jonboulle** [comment]
lgtm

**Comment by vbatts** [comment]
LGTM

**Pull request merged**
