### PR TITLE
MAINTAINERS: add Aleksa Sarai

### PR DESCRIPTION
**Pull request by vbatts**
Aleksa has been invaluable in both feedback, brainstorming and
fixes/features all the way through the stack.

From the initial vote thread of
https://groups.google.com/a/opencontainers.org/d/msg/dev/bfAysIHFDec/m3TqnW6kBQAJ
he recieved an LGTM from 5 of the 7 maintainers, though was requested to
have a more formal vote.

Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

- [x] @brendandburns
- [x] @jbouzane
- [x] @jonboulle
- [ ] @jstarks
- [x] @philips
- [x] @stevvooe
- [x] @vbatts

### CODE REVIEW

**Comment by vbatts** [comment]
LGTM

**Comment by philips** [comment]
LGTM

**Comment by jbouzane** [comment]
LGTM

**Comment by jonboulle** [comment]
LGTM

**Comment by brendandburns** [comment]
Lgtm

**Comment by brendandburns** [comment]
Lgtm

**Comment by wking** [comment]
On Tue, Aug 29, 2017 at 03:06:21PM +0000, Brendan Burns wrote:
> Lgtm

In this repo, PullApprove is configured to accept ‘LGTM’ or ‘lgtm’
(among some other values), but not the mixed-case Lgtm [1].  You can
also approve the PR with GitHub's review-approvals [2].  It may not
matter in this case though, since the PR has enough recognized
approvals for PullApprove (which doesn't have special rules for
two-thirds votes), and your intention with ‘Lgtm’ is pretty clear.

[1]: https://github.com/opencontainers/image-spec/blob/97ae57f204b5956aa313d453ead9094ff9056b32/.pullapprove.yml#L11
[2]: http://docs.pullapprove.com/groups/github_reviews/

**Comment by caniszczyk** [comment]
We now have 5/7 required votes for this to be merged in, I'll give it another 24 hours for any last votes from @stevvooe and @jstarks

**Comment by stevvooe** [comment]
LGTM

Just got back from PTO. Thanks @vbatts for sponsoring and creating the issue!

**Comment by caniszczyk** [comment]
Welcome @cyphar as an OCI image spec maintainer :)

**Comment by hqhq** [comment]
:congratulations:

**Comment by wking** [comment]
Someone may need to add @cyphar to the `image-spec-maintainers` group and/or kick PullApprove.  I notice that his LGTM [here][1] was not counted, and he's not listed in the #729 [approvers][2].

[1]: https://github.com/opencontainers/image-spec/pull/729#issuecomment-328679882
[2]: https://pullapprove.com/opencontainers/image-spec/pull-request/729/reviews/

**Comment by wking** [comment]
> ...he's not listed in the #729 approvers.

This seems to have been [fixed][1].

[1]: https://pullapprove.com/opencontainers/image-spec/pull-request/722/reviews/

**Pull request merged**
