### PR TITLE
config.md: clarify `command ENV` is an command of Dockerfile

### PR DESCRIPTION
**Pull request by coolljt0725**
If user doesn't know much about Dockerfile, the sentence `a command like ENV`
is confused, we should make it clear the `ENV` is an command of Dockerfile.

Singed-off-by: Lei Jitang leijitang@huawei.com

### CODE REVIEW

**Comment by coolljt0725** [comment]
@wking  updated

**Comment by wking** [comment]
642e6767 looks good to me, although I prefer the backticks and
doc-link from [1].

[1]: https://github.com/opencontainers/image-spec/pull/401#discussion_r84208538

**Comment by jonboulle** [comment]
Please add the doc-link as wking suggested.

**Comment by coolljt0725** [comment]
@jbouzane  done

**Comment by jonboulle** [comment]
lgtm

**Comment by wking** [comment]
d3c3afae looks good to me, although I prefer the backticks from [1]
;).

[1]: https://github.com/opencontainers/image-spec/pull/401#discussion_r84208538

**Comment by vbatts** [comment]
LGTM

**Pull request merged**
