### PR TITLE
Rename box repository in implementations.md

### PR DESCRIPTION
**Pull request by erikh**
The repository has moved and I would like to make sure the reference is current.

I hope this is a welcome change. Thank you!

### CODE REVIEW

**Comment by erikh** [comment]
So much for using the edit feature of github, no signature. :(

**Comment by stevvooe** [comment]
LGTM

**Comment by stevvooe** [comment]
@opencontainers/image-spec-maintainers PTAL

**Comment by vbatts** [comment]
LGTM

**Pull request merged**
