### PR TITLE
README: fix link syntax

### PR DESCRIPTION
**Pull request by jonboulle**
Signed-off-by: Jonathan Boulle <jonathanboulle@gmail.com>

### CODE REVIEW

**Comment by wking** [comment]
Heh, I guess everyone's been skimming over this section or reading the
Markdown source ;).  dd34672cc looks good to me.

**Comment by philips** [comment]
LGTM

**Comment by jonboulle** [comment]
LGTM (does this work?)

**Comment by wking** [comment]
On Wed, Oct 12, 2016 at 11:33:26AM -0700, Jonathan Boulle wrote:
> LGTM (does this work?)

Just for image-spec, and just because image-spec is rouge ;).  See
opencontainers/project-template#13 and
opencontainers/project-template#21.

**Pull request merged**
