### PR TITLE
schema: add more tests

### LINKED ISSUE #83: schema: define "negative" schema examples
We have several examples of well-formed JSON objects that pass schema validation, but no examples that fail. We need several for the following reason:

1. Ensure that schema validation is actually working.
2. Clarify aspects of the specification.

Ideally, these could be part of the specification and marked as bad, in congruence with the approach of having the examples validated.

Please see https://github.com/opencontainers/image-spec/pull/81#discussion_r64127544.

cc @s-urbaniak

### PR DESCRIPTION
**Pull request by s-urbaniak**
Currently samples in the specification are being tested. This adds
additional tests.

Signed-off-by: Sergiusz Urbaniak <sur@coreos.com>

Closes #83.

### CODE REVIEW

**Comment by philips** [comment]
It would be nice to have a doc explaining why each of the fail cases should fail to help future people understand.

**Comment by stevvooe** [comment]
> It would be nice to have a doc explaining why each of the fail cases should fail to help future people understand.

Agreed. Typically, I find these kinds of undocumented fixtures to be disorienting when they are introduced without context.

We can use the existing markdown parser. Add a `mustfail` flag to the markdown example extractor next to the mediatype.

**Comment by vbatts** [comment]
Perhaps those comments and such would be easier if the job blobs were just
byte array variables in a *_test.go file?

**Comment by stevvooe** [comment]
@vbatts `[]byte/string` is fine. We just need a little context to these (not these examples are wildly complex).

**Comment by stevvooe** [comment]
Edit: added that this closes #83.

**Comment by philips** [comment]
@s-urbaniak can you fixup these tests to include metadata on why they fail?

**Comment by philips** [comment]
*human readable metadata.

**Comment by s-urbaniak** [comment]
@philips @stevvooe @vbatts (travelling, having limited access to the internets) PTAL

**Comment by philips** [comment]
LGTM, thanks!

**Comment by philips** [comment]
I think this is ready to merge. Can other @opencontainers/image-spec-maintainers take a look and give an LGTM?

**Comment by vbatts** [comment]
LGTM

**Pull request merged**
