### PR TITLE
Fix "a the hashs" -> "the hash" typo

### PR DESCRIPTION
**Pull request by WeiZhang555**
Signed-off-by: Zhang Wei <zhangwei555@huawei.com>

### CODE REVIEW

**Comment by wking** [comment]
On Sun, Oct 09, 2016 at 01:55:33AM -0700, zhangwei_cs wrote:
>   * Fix typo

6f0d9a57 looks good to me, although:

  descriptor: Fix "a the hashs" -> "the hash" typo

would be a more specific commit message summary.

**Comment by WeiZhang555** [comment]
@wking git commit message is updated as suggested. :smile:

**Comment by jonboulle** [comment]
LGTM

**Comment by wking** [comment]
fd29eb3f looks even better to me ;).

**Comment by WeiZhang555** [comment]
@wking :laughing: :rocket:

**Comment by WeiZhang555** [comment]
@wking I think your "looks good to me" can't be detected by the "PullApprove" system, maybe you need to give a formal "LGTM" to make this PR green :stuck_out_tongue_winking_eye:

**Comment by jonboulle** [comment]
@WeiZhang555 he is not a [maintainer](https://github.com/opencontainers/image-spec/blob/master/MAINTAINERS) so it is not counted towards PullApprove

**Comment by philips** [comment]
LGTM

**Pull request merged**
