### PR TITLE
Remove Keyang Xie as a maintainer

### PR DESCRIPTION
**Pull request by caniszczyk**
Keyang Xie has been unresponsive and last made project activity was nearly 2 years ago.

We thank Keyang Xie for their contributions and he was instrumental in helping getting OCI off the ground.

See https://github.com/opencontainers/image-spec/issues/834

**This PR must get at least 6 LGTMs before merging:**

- [ ] Brendan Burns <bburns@microsoft.com> (@brendandburns)
- [x] Jon Johnson <jonjohnson@google.com> (@jonjohnsonjr)
- [ ] John Starks <jostarks@microsoft.com> (@jstarks)
- [ ] Jonathan Boulle <jon@nstack.com> (@jonboulle)
- [ ] Stephen Day <stevvooe@gmail.com> (@stevvooe)
- [x] Vincent Batts <vbatts@redhat.com> (@vbatts)
- [x] Aleksa Sarai <asarai@suse.de> (@cyphar)
- [x] Keyang Xie <keyang.xie@gmail.com> (@xiekeyang)

Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>

### CODE REVIEW

**Review by vbatts — APPROVED** [review]
Thank you, @xiekeyang for all your efforts and contributions

LGTM

**Comment by jonjohnsonjr** [comment]
LGTM

**Comment by cyphar** [comment]
LGTM. Thanks for your previous work on this project!

**Comment by xiekeyang** [comment]
Sorry for late response. I agree to be removed from maintainer list, for that I make few contribution to OCI these years.

Appreciate to everyone!

**Comment by cyphar** [comment]
In that case we can merge this as-is, we don't need a 2-3 vote if the maintainer themselves consents to being removed (at least that's how we've always done it in other OCI projects).

**Comment by caniszczyk** [comment]
Thanks @cyphar, I created https://github.com/opencontainers/image-spec/pull/851 to recognized previous maintainers as a thank you.

**Comment by stevvooe** [comment]
LGTM

@xiekeyang Hope you're doing well!

**Pull request merged**
