### PR TITLE
Remove validation warnings to stdout

### LINKED ISSUE #686: Fix the schema validation API
From https://github.com/opencontainers/image-spec/pull/491#issuecomment-302779611

an API like this:

```go
if err := validate(content); err != nil {
  for _, warning := range Warnings(err) {
    // do something with warnings
  }
}
```

We could define interfaces like this:

```go
type Warnings {
  Warnings() []error
}

type Errors {
  Errors() []error
}
```

Either of these could be asserted on the error returned from the validate function. We can define helpers for common cases. For example, the below would not take the error path when there are just warnings:

```go
if err := validate(content); err != nil && IgnoreWarnings(err) {
   // handle hard errors
}
```

### PR DESCRIPTION
**Pull request by sudo-bmitch**
Based on our discussion on the June 6th call, we decided to remove the warnings from the code and focus on only things that trigger an error. We had not been maintaining the existing warnings. Anything that only prints to stdout/stderr was deleted since it's unlikely anyone is using that. Private functions that only triggered a print to stdout were deleted.

If others want a stricter validation, those on the call felt it would be better for them to perform that themselves rather than adding new code for OCI to maintain.

Fixes #686.

### CODE REVIEW

**Review by tianon — APPROVED** [review]
Agreed, code that nobody is maintaining, ~nobody is using, and nobody (I'm aware of) is asking for is code that shouldn't exist, IMO!

**Review by Sec32fun32 — COMMENTED** [review]
#'nin kopyası

**Comment by dontlaugh** [comment]
@sudo-bmitch any chance of getting tag for this soon? Even an rc.

Otherwise, if you're targeting a release next year, I can probably convince my team to pin to a commit. A tag would be nicer, though.

Thanks for fixing this so fast, btw.

**Comment by tianon** [comment]
Our tags are for versions/releases of the spec, not the Go code that comes along for the ride, so it's not likely we'd do a release just for this.

When we looked at this, we couldn't find many public consumers of this code; can you share what you're using it for and what value it's providing to you?

**Comment by dontlaugh** [comment]
> so it's not likely we'd do a release just for this.

That's fine.

We use the function as one of our validation passes for image manifests, which is what we deal with most of the time in our implementation. Our API accepts a raw descriptor and this is a very early check to see if it's something we'll want to deal with.

```
	if err := schema.ValidatorMediaTypeManifest.Validate(reader); err != nil {
		return nil, err // bad request
	}
```

We do other validation (specific to our use case, like you all recommend) further down the call stack.

We aren't building an OCI-compliant API, but we do want to store compliant objects, so we're attracted to a json schema + some basic fields that's maintained upstream.

**Comment by sudo-bmitch** [comment]
I like the idea of periodically cutting patch releases, it's good to exercise the process. But that process requires a 2/3 majority of the maintainers which is a relatively heavy lift. So my personal advice would be to pin to a commit if you need something soon.

**Pull request merged**
