### PR TITLE
image-layout: add explanation of the refs directory use case for tags

### PR DESCRIPTION
**Pull request by philips**
Signed-off-by: Brandon Philips <brandon.philips@coreos.com>

### CODE REVIEW

**Comment by philips** [comment]
cc @runcom

**Comment by wking** [comment]
79d0c7f5 looks fine to me.

**Comment by runcom** [comment]
LGTM (IANAM)

**Comment by vbatts** [comment]
LGTM

**Comment by stevvooe** [comment]
@philips Are we not standardizing on the `refs/tags` convention?

**Comment by philips** [comment]
@stevvooe If you want to try and do that. I couldn't articulate a good reason for refs/tags besides "future use". So, I am fine with this as-is as long as an explanation is clear enough for @runcom who originally was confused around the use-case of refs.

**Comment by stevvooe** [comment]
LGTM

**Pull request merged**
