### PR TITLE
fixing code of conduct link

### PR DESCRIPTION
**Pull request by vsoch**
Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

### CODE REVIEW

**Comment by vsoch** [comment]
Okay, signed commit, pulled changes from master, and now the correct link `[code-of-conduct] instead of `(code-of-conduct)``. This is strangely both humiliating and enlightening about best practices for pull requests!

**Comment by vbatts** [comment]
:smile: 
LGTM
The travis failure is something unrelated (though needs to be looked into separately)

**Comment by vsoch** [comment]
Poor TravisCI (and all his helpful humans) have had it rough recently. :/

**Comment by vsoch** [comment]
Code of conduct link moved outside of .github folder, as discussed in OCI call.

**Comment by vbatts** [comment]
LGTM

**Comment by cyphar** [comment]
LGTM.

**Comment by vsoch** [comment]
hooray! :confetti_ball:

**Pull request merged**
