### PR TITLE
schema: slight clarification for oci-layout file

### PR DESCRIPTION
**Pull request by vbatts**
https://github.com/opencontainers/image-spec/pull/579#issuecomment-285132348

Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

### CODE REVIEW

**Comment by stevvooe** [comment]
LGTM

Maybe needs to rebase after merging the PR that fixes the build.

**Comment by vbatts** [comment]
rebased

**Comment by stevvooe** [comment]
LGTM

**Comment by stevvooe** [comment]
@jbouzane Pull approve does recognize the approvals system. You need to say "LGTM".

**Comment by xiekeyang** [comment]
The `schema/fs.go` might had better to be updated accordingly.

**Comment by vbatts** [comment]
@xiekeyang the `schema/fs.go` is now a PHONY target in the `Makefile`. It ought to be regenerated as needed for make targets. I wish we could delete the fs.go completely, and only generate it, but that would break `go get` or vendoring of this spec.

**Comment by xiekeyang** [comment]
Yeah, you are right. I mistook it.

**Comment by stevvooe** [comment]
LGTM

**Comment by jonboulle** [comment]
:+1:

**Pull request merged**
