### PR TITLE
specs-go: Image.Created uses a string type

### PR DESCRIPTION
**Pull request by jlbutler**
Modify History.Created and Image.Created to be of type time.Time so that creation times may be validated, compared, etc.

### CODE REVIEW

**Comment by stevvooe** [comment]
LGTM

Surprised that we don't have real tests for this but let's not hold up this PR.

@opencontainers/image-spec-maintainers PTAL

**Comment by jlbutler** [comment]
Nit, updated the comment for History.Created to describe layer creation time rather than image.

**Comment by vbatts** [comment]
LGTM

**Comment by jonboulle** [comment]
lgtm

**Comment by jlbutler** [comment]
This closes issue #517 , I neglected to tag it earlier.

**Comment by stevvooe** [comment]
@jlbutler Thanks for the contribution!

**Pull request merged**
