### PR TITLE
README.md: one sentence per line

### PR DESCRIPTION
**Pull request by coolljt0725**
Signed-off-by: Lei Jitang <leijitang@huawei.com>

### CODE REVIEW

**Comment by wking** [comment]
c83a59b looks good to me, although I'm also fine leaving these alone and moving to one line per sentence when we have some other reason to touch the line.

**Comment by philips** [comment]
LGTM

**Comment by jonboulle** [comment]
LGTM but needs rebase now, sorry

**Comment by coolljt0725** [comment]
@jonboulle  rebased

**Comment by jonboulle** [comment]
LGTM

**Comment by philips** [comment]
LGTM

**Pull request merged**
