### PR TITLE
typo fix

### PR DESCRIPTION
**Pull request by TrumanLing**
Signed-off-by: Ling FaKe <lingfake@huawei.com>

### CODE REVIEW

**Comment by philips** [comment]
LGTM

**Comment by wking** [comment]
8a695459 looks good to me, but a nicer commit message and PR summary
would be:

  README: Fix "can then discovered" -> "can then be discovered"

or some such ;).

**Comment by TrumanLing** [comment]
@wking thanks for your advice, and I have done that according to your advice.

**Comment by wking** [comment]
6304f583 looks even better to me ;).

**Comment by jonboulle** [comment]
LGTM (thanks for keeping us honest wking)

**Comment by stevvooe** [comment]
LGTM

**Pull request merged**
