### PR TITLE
test: manifest list backward compatibility

### PR DESCRIPTION
**Pull request by runcom**
Build on top of #151 and #152

commit https://github.com/opencontainers/image-spec/pull/154/commits/1d75bf1d48e216b66e86cc09bfbcb22154b4c702 adds manifest list test

### CODE REVIEW

**Comment by philips** [comment]
need to fix the formatting on both commits :-/

**Comment by runcom** [comment]
@philips fixed formatting in https://github.com/opencontainers/image-spec/pull/152 and rebased this PR (#152 should go first - after #151 )

**Comment by runcom** [comment]
@philips actually, this fix can go in w/o any dependency on other PR, PTAL

**Comment by philips** [comment]
LGTM

**Comment by vbatts** [comment]
LGTM

**Review by Ghostman2591 — APPROVED** [review]

**Pull request merged**
