### PR TITLE
MAINTAINERS: add Valentin Rothberg

### PR DESCRIPTION
**Pull request by cyphar**
This PR must get at least 5 LGTMs before merging:

- [ ] Brendan Burns <bburns@microsoft.com> (@brendandburns)
- [x] Jon Johnson <jonjohnson@google.com> (@jonjohnsonjr)
- [ ] John Starks <jostarks@microsoft.com> (@jstarks)
- [ ] Jonathan Boulle <jon@nstack.com> (@jonboulle)
- [ ] Stephen Day <stevvooe@gmail.com> (@stevvooe)
- [x] Vincent Batts <vbatts@redhat.com> (@vbatts)
- [x] Aleksa Sarai <asarai@suse.de> (@cyphar)

/cc @vrothberg 
Signed-off-by: Aleksa Sarai <asarai@suse.de>

### CODE REVIEW

**Comment by cyphar** [comment]
LGTM.

**Review by vbatts — APPROVED** [review]
LGTM

**Comment by vrothberg** [comment]
Thanks!

**Comment by jonjohnsonjr** [comment]
LGTM

**Comment by AkihiroSuda** [comment]
needs rebase

**Comment by vbatts** [comment]
I'm not sure that these three PR's for maintainers accurately surface a maintainer election process.

It seems that while just barely, we have had a re-kindled interaction among maintainers recently, spurred by this initial audit.
Though two of the nominees (vrothberg and tych0) are not really present in reviews, PRs or the calls. Lasker is present in discussion and the calls, but not in contributions.

I move that we close these (#841 #842 #844) and among the active contributors as we continue rekindling, we have a proper nomination.

**Comment by vrothberg** [comment]
If joining calls is a requirement, please make them work for more time zones.  Unless folks want to work until midnight, the EU is unable to join. Maybe alternate times per week?

While things seem to revive now, the image-spec was inactive for a long while, so I think there is a bit of a chicken and egg problem in getting a track record. I thought that these three PRs aimed to address that issue, following the call by the TOB for folks to step up; especially from companies in the ecosystem.

But if things are back to normal now, I am happy to close and contribute.

**Comment by vbatts** [comment]
sorry, my statement isn't just about the time since this was opened. I know that the time slot of the call is not ideal for CEST tz (we've been talking again of adjusting for that). Joining the call isn't strict criteria. Just looking at general involvement.

**Comment by vbatts** [comment]
Closing these three PRs (#841 #842 #844), so that adding/replacing maintainers can go through the regular nomination process

**Pull request closed without merging**
