### PR TITLE
fix inline html/markdown syntax

### PR DESCRIPTION
**Pull request by xiekeyang**
Signed-off-by: xiekeyang <xiekeyang@huawei.com>

### CODE REVIEW

**Comment by philips** [comment]
How is this a typo? markdown allows for intermixing html like this.

**Comment by xiekeyang** [comment]
> How is this a typo? markdown allows for intermixing html like this.
Seems it doesn't.
it shows on page as,   \`application/vnd.oci.image.layer.tar+gzip\` 
We want like,  `application/vnd.oci.image.layer.tar+gzip`

**Comment by wking** [comment]
On Sun, Sep 11, 2016 at 08:58:16PM -0700, Brandon Philips wrote:
> How is this a typo? markdown allows for intermixing html like this.

There are some rules about inline Markdown inside HTML not being
supported.  I haven't dug up a refernce in the Markdown spec, but you
can see the backtics not being converted to code tags in master [1].
So +1 for b0edca4b (although a more specific commit summary would be
nice ;).

[1]: https://github.com/opencontainers/image-spec/blob/d564f8ed01dca4da16fe7d1d0543419deda2f421/serialization.md#terminology

**Comment by xiekeyang** [comment]
Update commit summary.

**Comment by jonboulle** [comment]
lgtm

**Comment by philips** [comment]
LGTM

**Pull request merged**
