### PR TITLE
img: update img/build-diagram.png

### LINKED ISSUE #584: `image-spec/img/build-diagram.png` need to rebuild after `manifest-list -> image-index `
The `build-diagram.png` still has `manifest list` , we should change it to `image index`
ping @philips

### PR DESCRIPTION
**Pull request by jonboulle**
Renamed manifest list to image index. Fixes #584

Signed-off-by: Jonathan Boulle <jonathanboulle@gmail.com>

### CODE REVIEW

**Comment by stevvooe** [comment]
LGTM

**Comment by stevvooe** [comment]
@opencontainers/image-spec-maintainers

**Comment by jonboulle** [comment]
LGTM but that probably doesn't help

**Comment by philips** [comment]
LGTM

**Pull request merged**
