### PR TITLE
Makefile: add helpers for glide-vc and !glide installed

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by brendandburns** [comment]
LGTM

**Comment by vbatts** [comment]
What about installing glide itself?

**Comment by runcom** [comment]
It's not go gettable and requires to setup at least a temporary GOPATH to build it (or curl + sh which I personally don't want). @vbatts do you want me to change this to be built locally if not present?

**Comment by runcom** [comment]
@vbatts Done

**Comment by vbatts** [comment]
LGTM

**Comment by jonboulle** [comment]
lgtm

**Pull request merged**
