### PR TITLE
oci-image-tool: add README

### PR DESCRIPTION
**Pull request by vbatts**
Since this tool is usable on its own.

Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

### CODE REVIEW

**Comment by jonboulle** [comment]
Is this necessary? IMHO anyone poking around here would probably know how to get it (I don't like encouraging people to go get master, and adding "usage" will inevitably result in drift..)

**Comment by vbatts** [comment]
Good points. I do think it needs something

**Comment by jonboulle** [comment]
Maybe just suggest getting a tagged version and that they can run the tool
to explore the available commands etc.

**Comment by vbatts** [comment]
like so?

**Comment by jonboulle** [comment]
Sure.

**Comment by jonboulle** [comment]
lgtm

**Comment by philips** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/opencontainers/image-spec/pull-request/198/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=opencontainers/image-spec)

**Pull request merged**
