### PR TITLE
image-index: delete the extra fields

### PR DESCRIPTION
**Pull request by q384566678**
I do not understand why this field is added and it is not used.
Signed-off-by: zhouhao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by wking** [comment]
On Thu, Feb 16, 2017 at 10:33:00PM -0800, Zhou Hao wrote:
> I do not understand why this field is added and it is not used.

‘elements’ was part of the discussion in #533 and #546.  @vbatts meant
to drop it (see [1]), but looks like this bit slipped through.  +1 to
removing it.

[1]: https://github.com/opencontainers/image-spec/pull/533#issuecomment-277355950

**Comment by stevvooe** [comment]
Please rebase.

**Comment by q384566678** [comment]
rebased. PTAL

**Comment by stevvooe** [comment]
LGTM

**Comment by q384566678** [comment]
@vbatts @jonboulle @philips PTAL

**Comment by jonboulle** [comment]
LGTM

**Pull request merged**
