### PR TITLE
Update vbatts email address in MAINTAINERS

### PR DESCRIPTION
**Pull request by ImJasonH**
Noticed after seeing https://github.com/opencontainers/image-spec/pull/831

I used the email address on @vbatts' GitHub profile, please let me know if you prefer something else 😄 

edit: This also aligns with MAINTAINERS in [runtime-spec](https://github.com/opencontainers/runtime-spec/blob/9c848d91e8cf872e7453296832d66de6325e1e25/MAINTAINERS#L3) and [distribution-spec](https://github.com/opencontainers/distribution-spec/blob/f576ba2ceac1f37396d2b378117bc5cc95740c42/MAINTAINERS#L6), so that's probably good signal.

### CODE REVIEW

**Comment by vbatts** [comment]
LGTM

**Comment by cyphar** [comment]
LGTM.

**Comment by cyphar** [comment]
@vbatts Need to re-LGTM.

**Review by vbatts — APPROVED** [review]
LGTM

**Pull request merged**
