### PR TITLE
schema: start error message with lowercase

### PR DESCRIPTION
**Pull request by stevvooe**
Signed-off-by: Stephen Day <stephen.day@getcruise.com>

### CODE REVIEW

**Comment by cyphar** [comment]
LGTM (we should figure out what's wrong with the CI).

**Comment by vbatts** [comment]
LGTM
Do the linters not work on go1.9 now?

**Comment by vbatts** [comment]
LGTM

**Comment by vbatts** [comment]
lol pullapprove disapproves of me, i reckon

**Comment by stevvooe** [comment]
Merging. I am going to drop Go 1.9 support in another PR. I don't want to hunt that one down.

**Comment by stevvooe** [comment]
LGTM

(Admittedly, I am tricking the system, @caniszczyk, can you see what is happening with @vbatts?)

**Comment by jonboulle** [comment]
Fixed via #782

**Pull request closed without merging**
