### PR TITLE
Clarify that image is a `tar.gz` file

### PR DESCRIPTION
**Pull request by abitrolly**
Signed-off-by: Anatoli Babenia <anatoli@rainforce.org>

### CODE REVIEW

**Review by sudo-bmitch — CHANGES_REQUESTED** [review]
Is this a reference to image-layout.md? An image itself is not a tar.gz, though that's the standard format of packaging a filesystem layer when pushed to a registry. For the Layout, that's a specification for a directory structure where we say the following:

> This layout MAY be used in a variety of different transport mechanisms: archive formats (e.g. tar, zip), shared filesystem environments (e.g. nfs), or networked file fetching (e.g. http, ftp, rsync).

Since images can be transported in other formats, mainly by using a registry, I don't think this is correct for the image spec.

**Comment by abitrolly** [comment]
> Is this a reference to image-layout.md?

I still think about it as a reference to OCI Image format. I expect clear instructions from the spec - how to parse the image, which compression algorithms tools should support. I also want it to be clear in terminology, so that people refer to the same thing when they say "I downloaded OCI image from repository".

**Comment by sudo-bmitch** [comment]
But if you pull it from a registry, the image manifest and config is a json blob, not a tar.gz.

**Comment by abitrolly** [comment]
I don't know how pull protocol works. Is it a single unauthenticated HTTP GET that can be saved into file?

**Comment by sudo-bmitch** [comment]
It's defined in https://github.com/opencontainers/distribution-spec/. Most public registries require auth even if it's anonymous, but here's a request to a self hosted registry:

```
$ curl -sSL -H "Accept: application/vnd.docker.distribution.manifest.v2+json" -H "Accept: application/vnd.docker.distribution.manifest.list.v2+json" http://localhost:5000/v2/library/alpine/manifests/latest | jq 
.
{
  "manifests": [
    {
      "digest": "sha256:1304f174557314a7ed9eddb4eab12fed12cb0cd9809e4c28f29af86979a3c870",
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "platform": {
        "architecture": "amd64",
        "os": "linux"
      },
      "size": 528
    },
    {
      "digest": "sha256:5da989a9a3a08357bc7c00bd46c3ed782e1aeefc833e0049e6834ec1dcad8a42",
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "platform": {
        "architecture": "arm",
        "os": "linux",
        "variant": "v6"
      },
      "size": 528
    },
    {
      "digest": "sha256:0c673ee68853a04014c0c623ba5ee21ee700e1d71f7ac1160ddb2e31c6fdbb18",
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "platform": {
        "architecture": "arm",
        "os": "linux",
        "variant": "v7"
      },
      "size": 528
    },
    {
      "digest": "sha256:ed73e2bee79b3428995b16fce4221fc715a849152f364929cdccdc83db5f3d5c",
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "platform": {
        "architecture": "arm64",
        "os": "linux",
        "variant": "v8"
      },
      "size": 528
    },
    {
      "digest": "sha256:1d96e60e5270815238e999aed0ae61d22ac6f5e5f976054b24796d0e0158b39c",
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "platform": {
        "architecture": "386",
        "os": "linux"
      },
      "size": 528
    },
    {
      "digest": "sha256:fa30af02cc8c339dd7ffecb0703cd4a3db175e56875c413464c5ba46821253a8",
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "platform": {
        "architecture": "ppc64le",
        "os": "linux"
      },
      "size": 528
    },
    {
      "digest": "sha256:c2046a6c3d2db4f75bfb8062607cc8ff47896f2d683b7f18fe6b6cf368af3c60",
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "platform": {
        "architecture": "s390x",
        "os": "linux"
      },
      "size": 528
    }
  ],
  "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
  "schemaVersion": 2
}
```

**Comment by abitrolly** [comment]
That looks like manifest without blobs. So I can't call it the image.

**Comment by sudo-bmitch** [comment]
> That looks like manifest without blobs. So I can't call it the image.

That was the API to pull the manifest. You would run a similar API to pull the individual image manifest. And then the blob API to download each of the blobs. Registry servers do not package and send the image as a tar.gz file, they send the individual components, and clients can skip the push or pull of components that have previously been transferred. This is how a majority of images are pushed and pulled over the network.

**Comment by abitrolly** [comment]
So it is not the specification of the image then, but documentation of the API or exchange protocol. Historically an image always was a single file. ISO, HDD, or VM. I don't think it worth to break the terminology.

**Comment by sudo-bmitch** [comment]
I don't want to be the one that tries to get the container ecosystem to adopt a new term for this.

For now, I'm closing this PR because I don't believe it's a valid change.

**Comment by abitrolly** [comment]
> I don't want to be the one that tries to get the container ecosystem to adopt a new term for this.

I am not sure I understand you right. You don't want to use the name "OCI Image Format" for the structure of the image file?

I assume the ecosystem uses not very specific "image" reference, because Docker service model historically provided a hosted service through the API, and the details, how images are actually handled was hidden by CLI, and were implementation specific. But now, that people need tools to work with these images (https://github.com/wagoodman/dive etc.), there is a need to delineate this API and actual effective representation of images on disk. So that tool authors can spend less time on trying to reach interoperability and solve usual use cases - reduce startup time, processing overhead etc.

So I would expect [considerations](https://github.com/opencontainers/image-spec/blob/main/considerations.md) to include user stories, such as inspecting image contents (the way `dive` does), speeding up image startup (seekable targz), processing image on one go with minimal overhead for executing the image on low memory devices, streaming security scan, etc. And for that to be simple, the image needs to be a file.

**Comment by sudo-bmitch** [comment]
The OCI term for storing this content in a directory, that can optionally be transported as a tar or similar format, is OCI Image Layout. https://github.com/opencontainers/image-spec/blob/main/image-layout.md

I'm not a fan of "Image" in that term because a Layout can package multiple images, or things that aren't images at all. To me it's a local repository format. I'm also aware of others that want to use it for more than a single repository and treat it more like a local cache of images from external sources. Many tools use it to export or import a single image (over an air gap or from the build system).

Regardless of how it's used, this is the only format I'm aware of that packages the image on disk that can be optionally converted to a tar.gz.

**Pull request closed without merging**
