### PR TITLE
[ReadMe] Remove extraneous "should"

### PR DESCRIPTION
**Pull request by RobDolinMS**
Signed-off-by: Rob Dolin <robdolin@microsoft.com>

### CODE REVIEW

**Comment by philips** [comment]
LGTM

**Comment by philips** [comment]
cc @opencontainers/image-spec-maintainers

**Comment by jonboulle** [comment]
LGTM although it seems unnecessary

**Comment by jonboulle** [comment]
@robdolinms total nit but in future could you please omit the square brackets from your commit subjects? Eg `README: ...`  is more common

**Comment by wking** [comment]
On Fri, Sep 02, 2016 at 12:42:00PM -0700, Jonathan Boulle wrote:
> LGTM although it seems unnecessary 

@RobDolinMS like to grep for ‘should’ to make sure we're remembering
to CAPS it when we intend to make a formal recommendation ;).  See
also azurestandard/runtime-spec#536.

**Pull request merged**
