### PR TITLE
Fix the PullApprove approve_regex to cover more cases

### PR DESCRIPTION
**Pull request by caniszczyk**
'^(Approved|lgtm|LGTM|:shipit:|:star:|:\+1:|:ship:)'

Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>

### CODE REVIEW

**Comment by caniszczyk** [comment]
cc: @vbatts and sorry for the tooling churn, we will be better for it :)

**Comment by caniszczyk** [comment]
LGTM

**Comment by vbatts** [comment]
OHMAN

LGTM

**Comment by wking** [comment]
On Wed, Jun 01, 2016 at 01:02:42PM -0700, Chris Aniszczyk wrote:
> '^(Approved|lgtm|LGTM|:shipit:|:star:|:\+1:|:ship:)'

This is quite a few more cases ;).  Does it come with a corresponding
update to the docs [1]?  Personally I think lgtm/LGTM is sufficient.

[1]: https://github.com/opencontainers/project-template/blob/1d5bddcedef071152391137716db4bdbce012767/MAINTAINERS_GUIDE.md#who-decides-what

**Comment by jonboulle** [comment]
please, let the maintainers decide.

**Comment by jonboulle** [comment]
:ship:

**Comment by caniszczyk** [comment]
ah damn, did the PR wrong which fails the build, going to move discussion to a new PR:
https://github.com/opencontainers/image-spec/pull/106

**Pull request closed without merging**
