### PR TITLE
schema/fs: Drop *.go files

### PR DESCRIPTION
**Pull request by wking**
With:

    $ go get -u github.com/mjibson/esc
    $ make schema/fs.go

now that #538 has landed.

### CODE REVIEW

**Comment by vbatts** [comment]
while i like this idea, this also means the code can not be `go get`ten and vendor'ed, right?

**Comment by wking** [comment]
On Thu, Mar 09, 2017 at 11:07:37AM -0800, Vincent Batts wrote:
> while i like this idea, this also means the code can not be `go
> get`ten and vendor'ed, right?

This has no impact on ‘go get’, since all the schema/*.go is still
there.  All I'm doing is removing *.go which had been bundled into
fs.go.  All we use fs.go for is the *.json files, and those are
still there [1].

[1]: https://github.com/wking/image-spec/blob/5e79bb5ba4c9ab85f6e115372cb9608750dceab4/schema/fs.go#L205

**Comment by vbatts** [comment]
k. Prolly should add it to `.gitignore` too

**Comment by wking** [comment]
> Prolly should add it to .gitignore too

?  `fs.go` is still in version control after this commit.  I an only removing some unused content from `fs.go`.  What would I add to `.gitignore`.

**Comment by vbatts** [comment]
i misunderstood. I thought (hoped?) you meant that schema/fs.go is removed and only generated as needed.

**Comment by wking** [comment]
> ...only generated as needed

Well, only generated when `.json` changes (#538) should help a bit ;).

**Comment by jonboulle** [comment]
LGTM

> I thought (hoped?) you meant that schema/fs.go is removed and only generated as needed.

we could try this elsewhere but this change is fine for now

**Comment by vbatts** [comment]
LGTM

**Pull request merged**
