### PR TITLE
Fix the PullApprove approve_regex to cover more cases

### PR DESCRIPTION
**Pull request by caniszczyk**
'^(Approved|lgtm|LGTM|:shipit:|:star:|:\+1:|:ship:)'

Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>

### CODE REVIEW

**Comment by philips** [comment]
LGTM

**Comment by jonboulle** [comment]
Approved by me

**Comment by philips** [comment]
@caniszczyk is this some new build integration you did that is failing now?!

**Comment by wking** [comment]
On Wed, Jun 01, 2016 at 01:13:11PM -0700, Brandon Philips wrote:
> @caniszczyk is this some new build integration you did that is failing now?!

git-validation is old, and that's what's complaining [1].  @vbatts?

[1]: https://travis-ci.org/opencontainers/image-spec/builds/134561897#L236

**Comment by caniszczyk** [comment]
sorry at a conference where the wifi is equivalent of a 28k modem, not sure why it's failing

**Comment by wking** [comment]
On Wed, Jun 01, 2016 at 01:14:44PM -0700, W. Trevor King wrote:
> git-validation is old, and that's what's complaining [1].  @vbatts?
> 
> [1]: https://travis-ci.org/opencontainers/image-spec/builds/134561897#L236

Looks like a bug in Travis, with a workaround being to have more than
one commit in the PR [1].

[1]: https://github.com/travis-ci/travis-ci/issues/5133#issuecomment-157767638

**Comment by caniszczyk** [comment]
@wking thanks, going to push another commit to the PR and see if that does it

**Comment by vbatts** [comment]
@caniszczyk hold on that. See https://github.com/opencontainers/image-spec/pull/107

**Comment by caniszczyk** [comment]
@vbatts I just created another PR that will solve our problem https://github.com/opencontainers/image-spec/pull/108

**Comment by caniszczyk** [comment]
see https://github.com/opencontainers/image-spec/pull/108

**Pull request closed without merging**
