### PR TITLE
GOVERNANCE.md: fix typo

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by jonboulle** [comment]
LGTM

**Comment by wking** [comment]
f29d8bc9 looks good to me.  Can you file this change in
opencontainers/project-template too?

**Comment by philips** [comment]
@runcom this needs to be fixed in opencontainers/project-template too as wking says.

LGTM

**Comment by runcom** [comment]
> @runcom this needs to be fixed in opencontainers/project-template too as wking says.

already done https://github.com/opencontainers/project-template/issues/17 and merged

**Pull request merged**
