### PR TITLE
Expected type/subtype test for descriptors should have comment that is failure

### PR DESCRIPTION
**Pull request by vsoch**
Just kidding, I can't sleep at night because of these things :P 

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

### CODE REVIEW

**Comment by vsoch** [comment]
Looks like everything passed minus make .gitvalidation, here is from the makefile:

```
# When this is running in travis, it will only check the travis commit range
.gitvalidation:
	@which git-validation > /dev/null 2>/dev/null || (echo "ERROR: git-validation not found. Consider 'make install.tools' target" && false)
ifdef TRAVIS_COMMIT_RANGE
	git-validation -q -run DCO,short-subject,dangling-whitespace
else
	git-validation -v -run DCO,short-subject,dangling-whitespace -range $(EPOCH_TEST_COMMIT)..HEAD
endif
```
I'm not sure what this tool is, so let me know if I did something wrong on my end. I suspect the other PR test will fail too.

**Comment by cyphar** [comment]
Same problem as #794 -- the commit message subject is too long. If you make it shorter the tests won't fail. As with the other PR, LGTM otherwise.

**Comment by vbatts** [comment]
LGTM

**Comment by vbatts** [comment]
@cyphar same here regarding pattern-match on your approval

**Comment by vbatts** [comment]
@vsoch could you rebase this?

**Comment by vsoch** [comment]
@vbatts all set.

**Review by jonjohnsonjr — APPROVED** [review]

**Review by vbatts — APPROVED** [review]
✨

**Pull request merged**
