### PR TITLE
serialization: add language about whiteout

### PR DESCRIPTION
**Pull request by philips**
This fixes https://github.com/opencontainers/image-spec/issues/130

### CODE REVIEW

**Comment by stevvooe** [comment]
I think the only open item is the handling of opaque directories: https://github.com/docker/docker/blob/22aca92ee3503f811f813be4a1349ad8e67fbbdb/daemon/graphdriver/aufs/aufs.go#L369. From there, it looks like they are actually omitted.

In particular, we have the following case, assuming `/foo/bar` exists and has entries:

```
delete  dir  /foo/bar
add     dir  /foo/bar
add     file /foo/bar/data
```

Based on the specification, we get the following in the top-level tar:

```
/foo/.wh.bar
/foo/bar
/foo/bar/data
```

From my understanding of aufs/overlay, this is handled via opq, but these aren't transmitted in layers, currently.

**Comment by philips** [comment]
@stevvooe If the opaque directories aren't transmitted/handled what needs to be documented?

**Comment by stevvooe** [comment]
@philips We need to clarify how to represent that particular situation. I'll have to track this down.

**Comment by philips** [comment]
@stevvooe Can we merge this improvement and I will file a separate opaque issue for you to hunt down?

**Comment by stevvooe** [comment]
LGTM

**Comment by jonboulle** [comment]
LGTM

**Pull request merged**
