### PR TITLE
Add required to config-schema.json

### PR DESCRIPTION
**Pull request by q384566678**
Add the attributes that config must validate
Signed-off-by: zhouhao zhouhao@cn.fujitsu.com

### CODE REVIEW

**Comment by vbatts** [comment]
LGTM

**Comment by jonboulle** [comment]
Not sure why 818f8f4 is showing up in this PR. Could you rebase please?

**Comment by q384566678** [comment]
> Not sure why 818f8f4 is showing up in this PR. Could you rebase please? 

This is my mistake, has been modified.

**Comment by wking** [comment]
07fbe7c7a looks good to me.

**Comment by jonboulle** [comment]
lgtm

**Comment by vbatts** [comment]
LGTM

**Pull request merged**
