### PR TITLE
MAINTAINERS: add Tycho Andersen

### PR DESCRIPTION
**Pull request by cyphar**
This PR must get at least 5 LGTMs before merging:

- [ ] Brendan Burns <bburns@microsoft.com> (@brendandburns)
- [x] Jon Johnson <jonjohnson@google.com> (@jonjohnsonjr)
- [ ] John Starks <jostarks@microsoft.com> (@jstarks)
- [ ] Jonathan Boulle <jon@nstack.com> (@jonboulle)
- [x] Stephen Day <stevvooe@gmail.com> (@stevvooe)
- [x] Vincent Batts <vbatts@redhat.com> (@vbatts)
- [x] Aleksa Sarai <asarai@suse.de> (@cyphar)

/cc @tych0
Signed-off-by: Aleksa Sarai <asarai@suse.de>

### CODE REVIEW

**Comment by cyphar** [comment]
LGTM.

**Comment by tych0** [comment]
minor nit is that it's "sen" not "son", but the actual line in MAINTAINERS is correct, just the commit message is wrong. thanks!

**Comment by stevvooe** [comment]
LGTM

**Review by vbatts — DISMISSED** [review]
LGTM

**Comment by vbatts** [comment]
I'm not sure that these three PR's for maintainers accurately surface a maintainer election process.

It seems that while just barely, we have had a re-kindled interaction among maintainers recently, spurred by this initial audit.
Though two of the nominees (vrothberg and tych0) are not really present in reviews, PRs or the calls. Lasker is present in discussion and the calls, but not in contributions.

I move that we close these (#841 #842 #844) and among the active contributors as we continue rekindling, we have a proper nomination.

**Comment by tych0** [comment]
That's fine with me! It's unlikely I'll be able to attend weekly meetings due to other commitments at work, so if that's a qualifying factor best to go with someone else.

**Comment by vbatts** [comment]
sorry, my statement isn't just about the time since this was opened. I know that the time slot of the call is not ideal for CEST tz (we've been talking again of adjusting for that). Joining the call isn't strict criteria. Just looking at general involvement.

**Review by jonjohnsonjr — DISMISSED** [review]

**Comment by jonjohnsonjr** [comment]
@cyphar needs rebase

@jonboulle care to vote yea or nay?

**Comment by brendandburns** [comment]
From my perspective the approach proposed by @vbatts [above](https://github.com/opencontainers/image-spec/pull/841#issuecomment-877414910) makes more sense than canvassing for more LGTMs.

**Comment by vbatts** [comment]
Closing these three PRs (#841 #842 #844), so that adding/replacing maintainers can go through the regular nomination process

**Pull request closed without merging**
