### PR TITLE
travis: use a `make .gitvalidation` target

### PR DESCRIPTION
**Pull request by vbatts**
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

### CODE REVIEW

**Comment by vbatts** [comment]
though, this only has the pr not push CI...

**Comment by philips** [comment]
LGTM

@vbatts you have to LGTM your own stuff now :-P

**Comment by vbatts** [comment]
wait whut? I never do that, and thought I saw that is explicitly ignored?

**Comment by vbatts** [comment]
/me tries it
:shipit:

**Comment by vbatts** [comment]
omg

**Comment by wking** [comment]
On Wed, Jun 01, 2016 at 01:52:13PM -0700, Vincent Batts wrote:
> wait whut? I never do that, and thought I saw that is explicitly ignored?

Only in runC (opencontainers/runc#863) at the moment.

**Pull request merged**
