### PR TITLE
v0.5.0 bump

### PR DESCRIPTION
**Pull request by vbatts**
it appears i missed rev'ing the version for v0.4.0, so this is a jump from 0.3.0-dev -> v0.5.0

### CODE REVIEW

**Comment by wking** [comment]
Can we please get #257 into 0.5.0?

**Comment by vbatts** [comment]
Rebased to include #257

**Comment by wking** [comment]
On Mon, Sep 12, 2016 at 07:33:05AM -0700, Vincent Batts wrote:
> Rebased to include #257

Dropping the ChangeLog?

**Comment by vbatts** [comment]
@wking fixed

**Comment by vbatts** [comment]
oh wait
hurr

**Comment by vbatts** [comment]
woof. `git reflog` to the rescue.

**Comment by vbatts** [comment]
@wking where is the changelog branch?

**Comment by wking** [comment]
On Tue, Sep 13, 2016 at 12:42:12PM -0700, Vincent Batts wrote:
> @wking where is the changelog branch?

Oops, sorry.  Looks like nobody has written a ChangeLog here yet.  I
was confusing it with opencontainers/runtime-spec#557 (which has a
ChangeLog entry).

**Comment by vbatts** [comment]
Yeah, i fetched the runtime-spec changelog and cherry-picked it ... that
was a messy merge :-\ Hence git reflog ...

**Comment by philips** [comment]
LGTM

**Comment by jonboulle** [comment]
LGTM

**Review by Ghostman2591 — APPROVED** [review]

**Pull request merged**
