### PR TITLE
rename manifest_backwards_compatibility_test.go

### PR DESCRIPTION
**Pull request by xiekeyang**
This file test more types than manifest.

Signed-off-by: xiekeyang <xiekeyang@huawei.com>

### CODE REVIEW

**Comment by philips** [comment]
LGTM

**Comment by stevvooe** [comment]
LGTM

**Comment by stevvooe** [comment]
@xiekeyang Please rebase!

**Comment by xiekeyang** [comment]
@opencontainers/image-spec-maintainers Rebased, PTAL.

**Comment by stevvooe** [comment]
LGTM

**Comment by philips** [comment]
LGTM

**Pull request merged**
