### PR TITLE
Consistently version media types

### LINKED ISSUE #338: Media type v1 (or not) inconsistency
Currently we define `Descriptor` in `specs-go/descriptor.go`, but its media type in `specs-go/v1/mediatype.go` as `application/vnd.oci.descriptor.v1+json`.  It seems like we should decide whether the type is being versioned or not.

* If it is being versioned:
    * shift `Descriptor` to `specs-go/v1/descriptor.go`
* If it is not being versioned (because we are committing to eternal forward compat):
    * shift `MediaTypeDescriptor` to `specs-go/mediatype.go`, and
    * rename the media type to `application/vnd.oci.descriptor+json`

We have the same inconsistency for layers, where the media types are defined in `specs-go/v1/mediatype.go` but lack a `.v1` in the type string.

### PR DESCRIPTION
**Pull request by wking**
Version `Descriptor` and use .v1 for the layer media types defined in `specs-go/v1/mediatype.go`.

Fixes #338.

### CODE REVIEW

**Comment by philips** [comment]
LGTM

**Comment by jonboulle** [comment]
lgtm

**Comment by jonboulle** [comment]
Build is broken.

**Comment by wking** [comment]
On Fri, Sep 30, 2016 at 03:08:09AM -0700, Jonathan Boulle wrote:
> Build is broken.

Ah, I'd forgotten to change the package name when moving descriptor.go
into v1/ [1].  Fixed (and rebased onto the current master) with
7366057 → 4e31348.

[1]: https://travis-ci.org/opencontainers/image-spec/builds/163610950#L316

**Comment by jonboulle** [comment]
lgtm

**Comment by philips** [comment]
LGTM

**Comment by philips** [comment]
other @opencontainers/image-spec-maintainers PTAL

**Comment by vbatts** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/opencontainers/image-spec/pull-request/347/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=opencontainers/image-spec)

**Pull request merged**
