### PR TITLE
OPTIONAL field MAY be null

### PR DESCRIPTION
**Pull request by coolljt0725**
This field MAY be null is duplicate with the `OPTIONAL`

Signed-off-by: Lei Jitang <leijitang@huawei.com>

### CODE REVIEW

**Comment by jonboulle** [comment]
I think this was talked about in a previous issue somewhere - it's not quite redundant - the field being optional means it might not be present, but that's different to it being present but having an empty/null value.

**Comment by jonboulle** [comment]
Could probably do with a once-over of the spec to make sure we're consistent about this for all fields.

**Comment by coolljt0725** [comment]
>Could probably do with a once-over of the spec to make sure we're consistent about this for all fields.

+1 for this to make it more clear.

**Comment by coolljt0725** [comment]
@jonboulle  add a sentence to clarify this

**Comment by jonboulle** [comment]
@coolljt0725 how is this clearer than what was originally there? it's no longer in context

**Comment by coolljt0725** [comment]
@jonboulle  maybe I just misunderstood your point. I think all the `OPTIONAL` field could be null

**Comment by jonboulle** [comment]
That makes sense, but if so, I'd rather move it to the top of the
PROPERTIES section, and tweak the wording a bit -

Any OPTIONAL field MAY also be set to null, which is equivalent to being
unspecified.

**Comment by duglin** [comment]
To be be really anal:

`Any OPTIONAL field MAY also be set to null, which is equivalent to being absent.`

**Comment by wking** [comment]
On Fri, Sep 30, 2016 at 07:39:34AM -0700, Jonathan Boulle wrote:
> That makes sense, but if so, I'd rather move it to the top of the
> PROPERTIES section, and tweak the wording a bit -

If we can make a general rule of this (and that sounds good to me), I
think that rule belongs in the README or some other file to cover all
of our JSON, instead of making a rule that applies only to
application/vnd.oci.image.config.v1+json.

> Any OPTIONAL field MAY also be set to null, which is equivalent to
> being unspecified.

I like this wording^.  I've floated using ‘null’ (vs. leaving the
property off) as a way to explicitly set a property unlimited [1], but
that could be tedious to handle in Go and the idea hasn't caught on
yet.  @crosbymichael has also pushed for a distinction between ‘null’
and Go's default value [2]; I'm not clear on why, but it may impact
this as well.

[1]: https://github.com/opencontainers/runtime-spec/pull/499#issuecomment-226572995
[2]: https://github.com/opencontainers/runtime-spec/pull/576#issuecomment-248759913

**Comment by vbatts** [comment]
LGTM

**Comment by philips** [comment]
LGTM

**Pull request merged**
