### PR TITLE
Remove io/ioutil references

### LINKED ISSUE #943: Remove io/ioutil dependency
As noted in #942, package `io/ioutil` has been deprecated since Go 1.16.

Reference: https://go.dev/doc/go1.16#ioutil

### PR DESCRIPTION
**Pull request by austinvazquez**
Resolves #943 

Signed-off-by: Austin Vazquez <macedonv@amazon.com>

### CODE REVIEW

**Review by sudo-bmitch — APPROVED** [review]
LGTM. We'll have a merge conflict with #942, so we'll need to rebase one of these depending on which merges first.

**Comment by austinvazquez** [comment]
> LGTM. We'll have a merge conflict with #942, so we'll need to rebase one of these depending on which merges first.

Thanks @sudo-bmitch . @sajayantony totally fine either way. Lmk whichever is easier.

**Comment by sajayantony** [comment]
Let's get this merged in first. #942 still needs approval and I can rebase :)

**Review by sajayantony — APPROVED** [review]

**Comment by Eldogor447-ui** [comment]
CODEOWNERS

**Pull request merged**
