### PR TITLE
descriptor-test: add test

### PR DESCRIPTION
**Pull request by q384566678**
Signed-off-by: zhouhao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by wking** [comment]
a2dab39c7 looks good to me.

We probably also want a test with a valid URL to ensure that passes,
but I don't care if that happens in this PR or in followup work.

**Comment by q384566678** [comment]
@vbatts @jonboulle @stevvooe @philips PTAL

**Comment by stevvooe** [comment]
LGTM

**Comment by philips** [comment]
LGTM

**Pull request merged**
