### PR TITLE
Create EMERITUS.md to recognize old maintainers

### PR DESCRIPTION
**Pull request by caniszczyk**
Previous maintainers should be thanked for their work.

Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>

### CODE REVIEW

**Comment by vbatts** [comment]
Oh nice. I wondered if we would do this in the opencontainers/org repo or in each respective repo

**Comment by cyphar** [comment]
`gitvalidation` doesn't like the trailing whitespace in `EMERITUS.md` (first line).

**Comment by caniszczyk** [comment]
@vbatts for now my thought is to do it in each respective repo

**Comment by cyphar** [comment]
LGTM. I will submit a similar patch to runc as well.

**Pull request merged**
