### PR TITLE
Spec

### PR DESCRIPTION
**Pull request by OKEAMAH**

### CODE REVIEW

**Comment by tianon** [comment]
I appreciate the sentiment, but unfortunately due to the nature of the way Git stores files (and file history) this actually makes things worse, not better. 🙈

**Comment by sudo-bmitch** [comment]
I agree with Tianon, this gets a NACK from me.

**Review by OKEAMAH — COMMENTED** [review]
Ft

**Review by OKEAMAH — COMMENTED** [review]
T

**Review by OKEAMAH — COMMENTED** [review]
Thanks

**Pull request closed without merging**
