### PR TITLE
MAINTAINERS: add Keyang Xie

### PR DESCRIPTION
**Pull request by vbatts**
@xiekeyang has been involved and actively interested get the overall
quality and testing improved for the image-spec.

I'm for enabling this work to continue now as we have the v1.0.0 out and
the work for the certification working group will rely on this continued
focus.

Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

- [x] @brendandburns
- [x] @jbouzane
- [ ] @jonboulle
- [x] @jstarks
- [x] @philips
- [ ] @stevvooe
- [x] @vbatts
- [x] @cyphar

### CODE REVIEW

**Comment by vbatts** [comment]
(explicit) LGTM

**Comment by brendandburns** [comment]
LGTM



________________________________

**Comment by jstarks** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/opencontainers/image-spec/pull-request/729/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=opencontainers/image-spec)

**Comment by philips** [comment]
LGTM

**Comment by jbouzane** [comment]
LGTM

**Comment by cyphar** [comment]
LGTM

**Comment by caniszczyk** [comment]
Awesome thanks, we have enough votes for this to clear.

@jonboulle and @stevvooe feel free to LGTM, if not, tomorrow we will merge this in :)

**Comment by xiekeyang** [comment]
Thanks for everyone! I'm excited to be nominated to maintainer and would make more contribution.

**Comment by caniszczyk** [comment]
Welcome @xiekeyang

**Comment by hqhq** [comment]
Congrats @xiekeyang

**Pull request merged**
