### PR TITLE
Release v1.0.0

### PR DESCRIPTION
**Pull request by vbatts**
Vote for this release: https://groups.google.com/a/opencontainers.org/d/msg/dev/5uVsyNyPhvc/G6s4afXGBQAJ

No changes sense rc7 tag

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Can we update README and links as well in this PR?

**Comment by vbatts** [comment]
@AkihiroSuda what links and README changes are you referring to?

**Comment by AkihiroSuda** [comment]
"Roadmap" section of README.md 

> The GitHub milestones lay out the path to the OCI v1.0.0 release in late 2016.

**Comment by AkihiroSuda** [comment]
Links seems already updated in https://github.com/opencontainers/image-spec/commit/f2b1eb6d793a6d0f0ffbad8ebbc4cf59d2c8845c

**Comment by wking** [comment]
> Links seems already updated in f2b1eb6

You may want to pin [these][1] [links][2] to v1.0.0 (they're currently floating with master).

[1]: https://github.com/opencontainers/image-spec/blame/v1.0.0-rc7/README.md#L27
[2]: https://github.com/opencontainers/image-spec/blame/v1.0.0-rc7/spec.md#L45

**Comment by vbatts** [comment]
that can be post v1

**Comment by stevvooe** [comment]
@vbatts Could we clarify somewhere that 1.0 milestone does not cover the Go API? There are too many problems in the validation area to guarantee backwards compatibility.

**Comment by vbatts** [comment]
Go API of the ./schema/ or of the ./specs-go/ or both?

**Comment by stevvooe** [comment]
@vbatts I think that `./schema` is the only problem area.

**Comment by vbatts** [comment]
This needs another LGTM by tomorrow. 😍

**Comment by philips** [comment]
LGTM

**Comment by jbouzane** [comment]
LGTM

**Comment by brendandburns** [comment]
LGTM.

**Pull request merged**
