### PR TITLE
Use specs-go/v1 to reference media type instead of a contant string

### PR DESCRIPTION
**Pull request by coolljt0725**
Signed-off-by: Lei Jitang <leijitang@huawei.com>

### CODE REVIEW

**Comment by stevvooe** [comment]
LGTM

**Comment by glestaris** [comment]
I could be misunderstanding this, but there may be a reason behind explicitely using literals instead of constants. Otherwise a regression in a constant may go unoticed. I didn't look deep tho so I could be wrong about this.

**Comment by wking** [comment]
On Tue, Oct 18, 2016 at 03:18:04AM -0700, George Lestaris wrote:
> I could be misunderstanding this, but there may be a reason behind
> explicitely using literals instead of constants. Otherwise a
> regression in a constant may go unoticed. I didn't look deep tho so
> I could be wrong about this.

Can you describe a potential constant-regression workflow?  I'm
personally fine with using string literals instead of variable names,
but the only small difference I see in robustness is that the variable
names will be compared at compile time while the strings would only be
compared at runtime.  For a test suite, that's not a big deal (compile
time and runtime being so close together), but it certainly doesn't
seem like using variables would be a drop in robustness.

**Comment by stevvooe** [comment]
@glestaris This is using constants on one side of the map and moves to use literals on the other. We can add further constants in the future, but this analysis is really outside the scope of this PR.

**Comment by philips** [comment]
LGTM

**Pull request merged**
