### PR TITLE
Release v1.1.0

### PR DESCRIPTION
**Pull request by sajayantony**
# Mailing List 

This thread tracks the release votes: https://groups.google.com/a/opencontainers.org/g/dev/c/Cnk6H9C4aag

# Tag

e7f7c0c  as v1.1.0

# Changes

Last release for Image-spec was v1.02 -  https://github.com/opencontainers/image-spec/pull/878. 

 - For full diff from v1.0.2 - https://github.com/opencontainers/image-spec/compare/opencontainers:image-spec:v1.0.2...sajayantony:image-spec:release-v1.1.0

- Commits after the last v1.1.0-rc.6 - https://github.com/opencontainers/image-spec/compare/opencontainers:image-spec:v1.1.0-rc6...sajayantony:image-spec:release-v1.1.0

0a41c19  version: bump back to +dev - Sajay Antony
e7f7c0c  version: release v1.1.0 - Sajay Antony
d0f90e6  Clarify that subject references a separate DAG - Brandon Mitchell
8b1e951  version: bump back to +dev - Brandon Mitchell

Votes:

- [x] @jonjohnsonjr
- [x] @jonboulle
- [x] @stevvooe
- [x] @sudo-bmitch 
- [x] @sajayantony
- [x] @tianon
- [x] @vbatts
- [ ] @cyphar

Associated Distribution spec RP https://github.com/opencontainers/distribution-spec/pull/507

### CODE REVIEW

**Review by sudo-bmitch — APPROVED** [review]
LGTM

**Comment by sudo-bmitch** [comment]
For reference, here is the v1.1.0 milestone (the only open task at this time is to cut the release): https://github.com/opencontainers/image-spec/milestone/14?closed=1

**Comment by sudo-bmitch** [comment]
@jonjohnsonjr @jonboulle @stevvooe @tianon @vbatts @cyphar PTAL

**Review by tianon — APPROVED** [review]
I reviewed https://github.com/opencontainers/image-spec/compare/v1.1.0-rc6...e7f7c0ca69b21688c3cea7c87a04e4503e6099e2 and re-reviewed https://github.com/opencontainers/image-spec/compare/v1.0.2...e7f7c0ca69b21688c3cea7c87a04e4503e6099e2 and both LGTM for release of e7f7c0ca69b21688c3cea7c87a04e4503e6099e2 as v1.1.0 :heart: :+1:

**Review by jonboulle — APPROVED** [review]

**Review by vbatts — APPROVED** [review]
:goat:

**Review by stevvooe — APPROVED** [review]

**Review by jonjohnsonjr — APPROVED** [review]

**Comment by ab151670** [comment]
Es

**Pull request merged**
