### PR TITLE
image: convert colon to hypen for path digests.

### PR DESCRIPTION
**Pull request by sgotti**
Noticed trying to validate and unpack a (I think) valid oci image layout.

@philips @s-urbaniak Are there some tests for oci-image-tool in the work? I haven't written a test because probably a generic tests could have covered this.

### CODE REVIEW

**Comment by wking** [comment]
On Sun, Jun 26, 2016 at 11:43:10PM -0700, Simone Gotti wrote:
>   * image: convert colon to hypen for path digests.

I'd rather address this with #159 (which converts to colons here [1]).
I was waiting on “yeah, the cas/ref engines approach sounds good”
feedback before investing time in a directory-based backend and tests.

[1]: https://github.com/opencontainers/image-spec/pull/159/files#diff-b11cc21c1cf82254929b0e2e98cbd695R56

**Comment by sgotti** [comment]
@wking Sorry I lost that PR. I'll take a deep look at it (since I'm implementing an OCI store derived from the rkt one that is very similar to your interface and adds all the advanced features).

Feel free to close this.

Thanks!

**Comment by wking** [comment]
On Mon, Jun 27, 2016 at 02:02:21PM -0700, Simone Gotti wrote:
> … I'm implementing an OCI store derived from the rkt one that is
> very similar to your interface and adds all the advanced features…

I was curious about your advanced features, so I went hunting for the
similar rkt interface.  The closest thing I can find is [1], but it
seems to require a local disk to back the store and it has a much more
structured view of the stored content than #159's generic Engine
interfaces.

As it stands now, #159 only provides tar-backed implementations of
those interfaces, but if the general idea is approved I intend to add
interfaces for more of the transports listed in [2] (zip, directory,
HTTP, …).  I'm not sure I'm motivated enough to implement Engines
backed by the Docker registry API [3] (I'm not sure it's CAS-y
enough), but the goal with #159 was to separate the engine
implementation from the consumers as thoroughly as possible.

It's good not to go too far in that direction though, so if you have
consumer use-cases or Engine implementation targets that aren't
supported by the generic Engine interfaces I'm adding in #159, please
comment there and tell me ;).

[1]: https://godoc.org/github.com/coreos/rkt/store#Store
[2]: https://github.com/opencontainers/image-spec/blob/ca58cdfc7c8200c6c62287e677fadb0074cc29cc/image-layout.md#open-container-initiative-image-layout-specification
[3]: https://docs.docker.com/registry/spec/api/

**Comment by sgotti** [comment]
@wking yeah, Sorry but I wasn't arguing that your implementation needs advanced features :smile: but that, since I'm writing an oci-store that have advanced features required for an ondisk image cache (https://github.com/sgotti/oci-store) to be used by projects like rkt, with your proposal in #159 it'll be useful, also only as an exercise, to write an additional engine that uses it (so you can do an `oci-image-tool verify` on top it). The unique differences is that the image-layout looks tied to just one image per layout (the ref can be 'latest' 'v1.0.0' etc...) while the oci store is meant to be a multi application store so the ref will be something like `busybox:latest` so the engine should assume a 'default' application name.

If you're interested, as suggested by @runcom and @philips, I opened a topic here: https://groups.google.com/forum/#!topic/containers-dev/HPzM3KrRGbI

> [1]: https://godoc.org/github.com/coreos/rkt/store#Store

Yes that's the current rkt stores but it's very very tied to the appc/spec, that's the reason I'm trying to create a base one to be used by specialized stores like to oci and perhaps appc (v2) store.

**Comment by wking** [comment]
On Thu, Jun 30, 2016 at 01:32:38AM -0700, Simone Gotti wrote:
> The unique differences is that the image-layout looks tied to just
> one image per layout (the ref can be 'latest' 'v1.0.0' etc...) while
> the oci store is meant to be a multi application store so the ref
> will be something like `busybox:latest` so the engine should assume
> a 'default' application name.

The only thing stopping you from using ‘busybox:latest’ as a ref name
in image-layout formats is the charset restriction [1].  You could
certainly put busybox-latest and debian-latest refs in the same
image-layout archive.

And while compatability with image-layout is useful, there's no reason
for all Engine backends to be based on image-layout.  You're free to
use Redis for a refs.Engine, a custom HTTP API for a cas.Engine, etc.

> If you're interested, as suggested by @runcom and @philips, I opened
> a topic here:
> https://groups.google.com/forum/#!topic/containers-dev/HPzM3KrRGbI

Ah, the graphic that you use in [2] looks similar to [3] :).  I hadn't
included caching, and I wasn't aware of the “tree store” concept, but
now I'd suggest the following groupings:

1. Name → descriptor lookup (via “registry” in [3], or via refs.Engine
   in #159).  This mutable stuff is probably not worth caching.

2. Descriptor → CAS drilling (via “content addressable storage” in
   [3], or via cas.Engine in #159).  This is easily cachable, and you
   can layer on as many caching algorithms as you like with something
   like:

     directEngine, err := docker.NewEngine("docker://registry-1.docker.io/")
     cachePath := "/var/lib/cas"
     engine, err := cache.NewEngine(cachePath, directEngine)
     reader, err := engine.Get("sha256:5b0bcabd1ed22e9fb1310cf6c2dec7cdef19f0ad69efa1f392e94a4333501270")

   where the cache engine will check it's local cachePath for the blob
   first, and only hit directEngine on misses.

3. Unpacking/rendering (“unpack” in [3], “render” in [2]).  The
   interface here can be Unpack(casEngine, destination), although
   pulling that public function out of image/unpack will probably be a
   post-#159 PR.  This can use a tree store to transparently cache
   unpacked trees just like (2) can use cache.NewEngine to
   transparently cache CAS objects.

[1]: https://github.com/opencontainers/image-spec/blob/ca58cdfc7c8200c6c62287e677fadb0074cc29cc/image-layout.md#open-container-initiative-image-layout-specification
[2]: https://docs.google.com/document/d/1dd19t2bMdnRnpdP-eYLzbhPO1NYYP1M1Xo6YQfhAxRw/edit
[3]: https://github.com/opencontainers/image-spec/issues/88#issue-156781487

**Comment by sgotti** [comment]
@wking Thanks for your detailed answer, I have some doubts that I'd like to clarify. Can we move this to the containers-dev@googlegroups.com topic (or the github #88 issue)? It seems to me the better place.

**Comment by wking** [comment]
On Thu, Jun 30, 2016 at 12:03:59PM -0700, Simone Gotti wrote:
> Can we move this to the containers-dev@googlegroups.com topic…

Done.

**Pull request closed without merging**
