### PR TITLE
image-layout: Fixed a typo in the example.

### PR DESCRIPTION
**Pull request by qianzhangxa**

### CODE REVIEW

**Comment by jonboulle** [comment]
LGTM, but can you squash the commits together?

**Comment by qianzhangxa** [comment]
Thanks @jonboulle. But I am not sure how I can squash the commits together, should I do it here? Or in my forked repo?

**Comment by jonboulle** [comment]
Squash in your fork and force-push

**Comment by qianzhangxa** [comment]
Done.

**Comment by stevvooe** [comment]
LGTM

**Comment by stevvooe** [comment]
Actually, needs a rebase.

**Comment by qianzhangxa** [comment]
Rebased.

**Comment by jonboulle** [comment]
LGTM, again

**Comment by stevvooe** [comment]
LGTM

**Pull request merged**
