### PR TITLE
schema: add checkPlatform

### PR DESCRIPTION
**Pull request by q384566678**
Fixes https://github.com/opencontainers/image-tools/pull/39
Signed-off-by: zhouhao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by stevvooe** [comment]
LGTM

**Comment by wking** [comment]
acf4adc37 looks good to me, although this is not really about
validating descendants (especially for the config platform check).  It
would be nice to have something like #403 land soonish so we had a
generic name for this sort of media-type-map-based verification.

**Comment by q384566678** [comment]
@philips @vbatts @jonboulle @stevvooe  PTAL

**Comment by jonboulle** [comment]
These are SHOULDs, not MUSTs. Why should we validate them?
https://github.com/opencontainers/image-spec/blame/master/config.md#L63

**Comment by vbatts** [comment]
i'm okay with them being _checked_, but not to FAIL a validation.

**Comment by wking** [comment]
On Wed, Nov 30, 2016 at 01:42:16PM -0800, Vincent Batts wrote:
> i'm okay with them being _checked_, but not to FAIL a validation.

+1.  We should probably table this until we settle on strict handling
(see the discussion in opencontainers/image-spec#452 and me trying to
outline the issue in opencontainers/image-tools#66).

**Comment by q384566678** [comment]
> These are SHOULDs, not MUSTs. Why should we validate them?

Because these two are required attributes, and as the specification says: **The name of the operating system which the image is built to run on**.  If it is the verification of the system, only by JSON to restrict the type is not rigorous, it should be the value of its specific judgment.

**Comment by q384566678** [comment]
Due to my mistakes, resulting in this PR can not be updated, I will close this, and then open a new PR.

**Pull request closed without merging**
