### PR TITLE
Set up Dependabot for github-actions dependencies 

### PR DESCRIPTION
**Pull request by mmorel-35**

### CODE REVIEW

**Comment by vbatts** [comment]
Hi @mmorel-35 !

What exactly does this accomplish?

**Comment by mmorel-35** [comment]
Hi @vbatts, it creates a PR (every week) when there is a new version of a github-action. You can learn more [here](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/keeping-your-actions-up-to-date-with-dependabot)

**Comment by vbatts** [comment]
Sounds good. Can you add that one sentence explanation and link into the commit, when you fixup the DCO as well?

`git commit -s --ammend .`

**Review by Clyderambo87 — DISMISSED** [review]

**Review by vbatts — APPROVED** [review]
🍨

**Pull request closed without merging**
