### PR TITLE
specs-go/v1: use correct field type for diff ids

### PR DESCRIPTION
**Pull request by stevvooe**
Signed-off-by: Stephen J Day <stephen.day@docker.com>

### CODE REVIEW

**Comment by xiekeyang** [comment]
It seems good to me. CI is failed because its deadline value inappropriate. I present the fix patch in #619

**Comment by stevvooe** [comment]
@xiekeyang Fixed.

**Comment by xiekeyang** [comment]
LGTM

**Comment by jonboulle** [comment]
lgtm

**Comment by jbouzane** [comment]
LGTM

**Pull request merged**
