### PR TITLE
README.md: move a line to spec.md

### PR DESCRIPTION
**Pull request by coolljt0725**
Signed-off-by: Lei Jitang <leijitang@huawei.com>

### CODE REVIEW

**Comment by wking** [comment]
I think that line should stay in the README.  The scope table is really guidance from the TOB to project maintainers about what should go in the spec, it's not part of the spec itself.

**Comment by coolljt0725** [comment]
I think the line 
`The _optional_ and _base_ layers of all OCI projects are tracked in the [OCI Scope Table](https://www.opencontainers.org/governance/oci-scope-table).`
should next to https://github.com/opencontainers/image-spec/pull/488/files#diff-958e7270f96f5407d7d980f500805b1bL49

**Comment by wking** [comment]
On Fri, Dec 09, 2016 at 09:20:27PM -0800, Lei Jitang wrote:
> I think the line `The _optional_ and _base_ layers of all OCI
> projects are tracked in the [OCI Scope
> Table](https://www.opencontainers.org/governance/oci-scope-table).`
> should next to
> https://github.com/opencontainers/image-spec/pull/488/files#diff-958e7270f96f5407d7d980f500805b1bL49

Moving the Scope Table link next to the spec's mention of
optional/base is reasonable, but I'd still rather keep this guiding
doc in the non-spec, project-structure section of the repo.  If the
consensus is to move it into the spec, we'll want to be very clear
that the Scope Table is not normative (because it's not maintained by
the image-spec maintainers, it's not versioned, and we can't link to a
pinned version of it).

And I doubt the Scope Table will be particularly interesting once the
spec's compliance language grows the “Protocols defined by this
specification are” section that we currently have in runtime-spec
[1,2].  The scope table will just be “if you want to read these
protocols again in language written by people less closely tied to the
spec…” ;).

[1]: https://github.com/opencontainers/image-spec/pull/381#discussion_r85947950
[2]: https://github.com/opencontainers/runtime-spec/blame/v1.0.0-rc2/README.md#L30

**Comment by stevvooe** [comment]
This is meant for the readme, not the spec.

**Pull request closed without merging**
