### PR TITLE
validate.go: add the verification content

### PR DESCRIPTION
**Pull request by q384566678**
According to [this](https://github.com/opencontainers/image-spec/blame/master/manifest.md#L57-60)  modified.
Signed-off-by: zhouhao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by q384566678** [comment]
Here I have a doubt that there is no reason for the validation of the mediatype field, because the mediatype field is optional and not always present in the descriptor.

**Comment by wking** [comment]
48fcec2 looks good to me.

**Comment by stevvooe** [comment]
It might be better to combine this into a function that tells whether or not a mediatype is a layer, although, this validation may be too strict.

**Comment by q384566678** [comment]
> It might be better to combine this into a function that tells whether or not a mediatype is a layer, although, this validation may be too strict.

@stevvooe The judgment here is only a warning, not an error. So it can not be said that the conditions are not layers.So I do not think your idea is good.

**Comment by vbatts** [comment]
LGTM

**Comment by cyphar** [comment]
@wking As @q384566678 said, this is only a warning -- the discussion inside opencontainers/image-tools#111 is not completely valid (this schema validator is not meant to error on unknown layer types).

**Comment by q384566678** [comment]
ping @philips @jonboulle @stevvooe

**Comment by jonboulle** [comment]
lgtm

**Comment by stevvooe** [comment]
As @cyphar said, this is probably too aggressive.

**Pull request merged**
