### PR TITLE
pandoc: point to a joint OCI org image

### PR DESCRIPTION
**Pull request by vbatts**
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

### CODE REVIEW

**Review by cyphar — APPROVED** [review]
LGTM.

**Comment by jonjohnsonjr** [comment]
Can we merge this?

**Comment by vbatts** [comment]
LGTM

**Comment by vbatts** [comment]
(i can't self approve ;-))

**Comment by jonjohnsonjr** [comment]
@brendandburns @jbouzane @jstarks @jonboulle @stevvooe @xiekeyang 

Can any of you approve this? CI is currently non-deterministically broken by Docker Hub rate limiting:

> $ docker pull vbatts/pandoc
> Using default tag: latest
> Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
> The command "docker pull vbatts/pandoc" failed and exited with 1 during .

**Review by samuelkarp — APPROVED** [review]

**Review by jstarks — APPROVED** [review]

**Review by fuweid — APPROVED** [review]
LGTM

**Comment by fuweid** [comment]
@vbatts two approvals and ready to merge :)

**Pull request merged**
