### PR TITLE
image: reduce permissions on mkdir

### PR DESCRIPTION
**Pull request by vbatts**
This was causing a lint failure https://travis-ci.org/opencontainers/image-spec/builds/148403656#L247

Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

### CODE REVIEW

**Comment by vbatts** [comment]
ping @opencontainers/image-spec-maintainers so we can clear up travis failures

**Comment by stevvooe** [comment]
@vbatts Shouldn't these honor umask?

**Comment by vbatts** [comment]
that is beside the point. The linter is failing because os.Mkdir of 0777 is
too open

**Comment by stevvooe** [comment]
@vbatts My local umask, for example, is 022. `0777 & (~022) == 0755`. The whole point of `umask` is leave the permissions of created resources up to the user.

Directory permissions levels are based on the design need. In this case, we defer to `0777` to say the user has control with `umask`.

Is this a broken linter or a too permissive directory permissions?

**Comment by vbatts** [comment]
i get umasks. perhaps the linter is strict here, but there is no reason to have a `0777` permission directory.

**Comment by vbatts** [comment]
the gometalinter is using the https://github.com/HewlettPackard/gas tool, which a perms check.
Not sure how to just loosen up that one rule.
@jonboulle @s-urbaniak ideas?

**Comment by stevvooe** [comment]
> i get umasks.

I know. Sorry if it came off that way.

`0755` is probably okay here, but `0700` is way too locked down. There are some use cases where user may want to create `0755` by setting mask to `0022` to allow group read, which is impossible with `0700` base mask for the creation.

Either way, we should be selecting permissions based on use case. A linter isn't the right way to enforce this.

**Comment by vbatts** [comment]
agreed

**Comment by philips** [comment]
@vbatts LGTM after you 0755 the thing; which is the conclusion I think you and @stevvooe came to.

**Comment by vbatts** [comment]
OK, updated. PTAL so we can clear the CI failures.

**Comment by vbatts** [comment]
weird CI failure. Now green.

**Comment by stevvooe** [comment]
LGTM

**Comment by jonboulle** [comment]
lgtm

**Pull request merged**
