### PR TITLE
[Media Types] Remove "combined" from image

### PR DESCRIPTION
**Pull request by RobDolinMS**
Removes the "...combined" media type from the image near the bottom of the Media-Types.md page.
Replaces the .PNG image file as well as edits the [.DOT](https://en.wikipedia.org/wiki/DOT_(graph_description_language)) file

Signed-off-by: Rob Dolin <robdolin@microsoft.com>

### CODE REVIEW

**Comment by wking** [comment]
ad1c7fbf looks good to me, although I'd squash the delete- and
replace-image commits together.

**Comment by philips** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/opencontainers/image-spec/pull-request/249/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=opencontainers/image-spec)

**Comment by philips** [comment]
cc @opencontainers/image-spec-maintainers

**Comment by stevvooe** [comment]
LGTM

**Pull request merged**
